openapi: 3.0.0
info:
  title: API Gateway
  description: | 
    - 1.0.0: API Gateway for Ewallet System Initial Version
      + User: Signup, login, logout, update profile, get profile, change password, reset password, link, link-confirm, unlink, get links, get wallets, get wallet detail
      + Wallet: topup, withdraw, transferp2p, get transaction history, get transaction detail
      + Authentication: refresh token
  version: 1.0.0
servers:
  - url: "http://localhost:8080/wallet/api"
    description: Endpoint for all external request to our wallet system
tags:
  - name: user
    description: System operations for user
  - name: wallet
    description: System operation for wallet
  - name: authentication
    description: System operation for authentication
components:
  schemas:
    sch_status_error:
      type: object
      properties:
        status_code:
          type: string
        error_desc:
          type: string
    sch_response_status:
      type: object
      properties:
        code:
          type: string
        code_desc:
          type: string
        text_disp:
          type: string
    sch_token:
      type: object
      properties:
        token:
          type: string
        refresh_token:
          type: string
    sch_user_info:
      type: object
      properties:
        id:
          type: string
        mobile:
          type: string
        name:
          type: string
        email:
          type: string
        isKyc:
          type: boolean
        hasLink:
          type: boolean
        role:
          type: string
    sch_user_profile:
      type: object
      properties:
        full_name:
          type: string
        email:
          type: string
        dob:
          type: string
        address:
          type: string
        origin_address:
          type: string
        national_id:
          type: string
        nation:
          type: string
    sch_wallet:
      type: object
      properties:
        id:
          type: string
        balance:
          type: integer
        wallet_type:
          type: string
    sch_link:
      type: object
      properties:
        bank_code:
          type: string
        link_info:
          type: object
          properties:
            source_no:
              type: string
            source_type:
              type: string
            expire_date:
              type: string
            national_id:
              type: string
  parameters:
    param_device_id:
      name: device_id
      in: path
      required: true
      description: unique identify of device
      schema:
        type: string
    param_otp_id:
      name: otp_id
      in: path
      required: true
      description: otp id for verify otp from user
      schema:
        type: string
    param_user_id:
      name: user_id
      in: path
      required: true
      description: user id
      schema:
        type: string
  requestBodies:
    body_otp_verify:
      description: body for verify otp
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              otp:
                type: string
    body_signup:
      description: body for signup
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              mobile:
                type: string
              password:
                type: string
    body_signin:
      description: body for signin
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              mobile:
                type: string
              password:
                type: string
    body_update_profile:
      description: body for profile
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/sch_user_profile"
    body_change_password:
      description: body for changing user password
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              password:
                type: string
              new_password:
                type: string
  responses:
    response_status_error:
      description: http status error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/sch_status_error"
    response_signup:
      description: response for signup
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                $ref: "#/components/schemas/sch_response_status"
              data:
                type: object
                properties:
                  otp_id:
                    type: string
    response_verify_otp:
      description: reponse for request verify otp
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                $ref: "#/components/schemas/sch_response_status"
    response_signin:
      description: response for signin request
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                $ref: "#/components/schemas/sch_response_status"
              data:
                type: object
                properties:
                  tokens:
                    $ref: "#/components/schemas/sch_token"
                  user_info:
                    $ref: "#/components/schemas/sch_user_info"
    response_status_only:
      description: response for update profile request
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                $ref: "#/components/schemas/sch_response_status"
    response_get_profile:
      description: response for get user profile request
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                $ref: "#/components/schemas/sch_response_status"
              data:
                type: object
                properties:
                  profile:
                    type: object
                    $ref: "#/components/schemas/sch_user_profile"
    response_get_wallet:
      description: reponse for get user wallets
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                $ref: "#/components/schemas/sch_response_status"
              data:
                type: object
                properties:
                  wallets:
                    type: array
                    items:
                      $ref: "#/components/schemas/sch_wallet"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /v1/devices/{device_id}/signup:
    parameters:
      - $ref: "#/components/parameters/param_device_id"
    post:
      tags:
        - user
      summary: create a wallet
      requestBody:
        $ref: "#/components/requestBodies/body_signup"
      responses:
        default:
          $ref: "#/components/responses/response_status_error"
        200:
          $ref: "#/components/responses/response_signup"
  /v1/devices/{device_id}/signup/otp/{otp_id}:
    parameters:
      - $ref: "#/components/parameters/param_device_id"
      - $ref: "#/components/parameters/param_otp_id"
    post:
      tags:
        - user
      summary: verify otp signup
      requestBody:
        $ref: "#/components/requestBodies/body_otp_verify"
      responses:
        default:
          $ref: "#/components/responses/response_status_error"
        200:
          $ref: "#/components/responses/response_verify_otp"
  /v1/devices/{device_id}/signin:
    parameters:
      - $ref: "#/components/parameters/param_device_id"
    post:
      tags:
        - user
      summary: sign in
      requestBody:
        $ref: "#/components/requestBodies/body_signin"
      responses:
        default:
          $ref: "#/components/responses/response_status_error"
        200:
          $ref: "#/components/responses/response_signin"
  /v1/devices/{device_id}/user/{user_id}/update_profile:
    parameters:
      - $ref: "#/components/parameters/param_device_id"
      - $ref: "#/components/parameters/param_user_id"
    post:
      tags:
        - user
      summary: update user profile
      security:
        - bearerAuth: []
      requestBody:
        $ref: "#/components/requestBodies/body_update_profile"
      responses:
        default:
          $ref: "#/components/responses/response_status_error"
        200:
          $ref: "#/components/responses/response_status_only"
  /v1/devices/{device_id}/user/{user_id}/get_profile:
    parameters:
      - $ref: "#/components/parameters/param_device_id"
      - $ref: "#/components/parameters/param_user_id"
    get:
      tags:
        - user
      summary: get user profile
      security:
        - bearerAuth: []
      responses:
        default:
          $ref: "#/components/responses/response_status_error"
        200:
          $ref: "#/components/responses/response_get_profile"
  /v1/devices/{device_id}/user/{user_id}/change_password:
    parameters:
      - $ref: "#/components/parameters/param_device_id"
      - $ref: "#/components/parameters/param_user_id"
    patch:
      tags:
        - user
      summary: change user password
      security:
        - bearerAuth: []
      responses:
        default:
          $ref: "#/components/responses/response_status_error"
        200:
          $ref: "#/components/responses/response_status_only"
      requestBody:
        $ref: "#/components/requestBodies/body_change_password"
  /v1/devices/{device_id}/user/{user_id}/wallets:
    parameters:
      - $ref: "#/components/parameters/param_device_id"
      - $ref: "#/components/parameters/param_user_id"
    get:
      tags:
        - user
      summary: get wallets of user
      security:
        - bearerAuth: [ ]
      responses:
        default:
          $ref: "#/components/responses/response_status_error"
        200:
          $ref: "#/components/responses/response_get_wallet"












